//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/wasm/v1beta1/genesis.proto

package jmes.wasm.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun contract(block: jmes.wasm.v1beta1.ContractKt.Dsl.() -> Unit): jmes.wasm.v1beta1.Genesis.Contract =
  jmes.wasm.v1beta1.ContractKt.Dsl._create(jmes.wasm.v1beta1.Genesis.Contract.newBuilder()).apply { block() }._build()
object ContractKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.wasm.v1beta1.Genesis.Contract.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.wasm.v1beta1.Genesis.Contract.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.wasm.v1beta1.Genesis.Contract = _builder.build()

    /**
     * <code>.jmes.wasm.v1beta1.ContractInfo contract_info = 1 [(.gogoproto.nullable) = false];</code>
     */
    var contractInfo: jmes.wasm.v1beta1.Wasm.ContractInfo
      @JvmName("getContractInfo")
      get() = _builder.getContractInfo()
      @JvmName("setContractInfo")
      set(value) {
        _builder.setContractInfo(value)
      }
    /**
     * <code>.jmes.wasm.v1beta1.ContractInfo contract_info = 1 [(.gogoproto.nullable) = false];</code>
     */
    fun clearContractInfo() {
      _builder.clearContractInfo()
    }
    /**
     * <code>.jmes.wasm.v1beta1.ContractInfo contract_info = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the contractInfo field is set.
     */
    fun hasContractInfo(): kotlin.Boolean {
      return _builder.hasContractInfo()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class ContractStoreProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .jmes.wasm.v1beta1.Model contract_store = 2 [(.gogoproto.nullable) = false];</code>
     */
     val contractStore: com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Model, ContractStoreProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getContractStoreList()
      )
    /**
     * <code>repeated .jmes.wasm.v1beta1.Model contract_store = 2 [(.gogoproto.nullable) = false];</code>
     * @param value The contractStore to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addContractStore")
    fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Model, ContractStoreProxy>.add(value: jmes.wasm.v1beta1.Genesis.Model) {
      _builder.addContractStore(value)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Model contract_store = 2 [(.gogoproto.nullable) = false];</code>
     * @param value The contractStore to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignContractStore")
    inline operator fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Model, ContractStoreProxy>.plusAssign(value: jmes.wasm.v1beta1.Genesis.Model) {
      add(value)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Model contract_store = 2 [(.gogoproto.nullable) = false];</code>
     * @param values The contractStore to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllContractStore")
    fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Model, ContractStoreProxy>.addAll(values: kotlin.collections.Iterable<jmes.wasm.v1beta1.Genesis.Model>) {
      _builder.addAllContractStore(values)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Model contract_store = 2 [(.gogoproto.nullable) = false];</code>
     * @param values The contractStore to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllContractStore")
    inline operator fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Model, ContractStoreProxy>.plusAssign(values: kotlin.collections.Iterable<jmes.wasm.v1beta1.Genesis.Model>) {
      addAll(values)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Model contract_store = 2 [(.gogoproto.nullable) = false];</code>
     * @param index The index to set the value at.
     * @param value The contractStore to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setContractStore")
    operator fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Model, ContractStoreProxy>.set(index: kotlin.Int, value: jmes.wasm.v1beta1.Genesis.Model) {
      _builder.setContractStore(index, value)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Model contract_store = 2 [(.gogoproto.nullable) = false];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearContractStore")
    fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Model, ContractStoreProxy>.clear() {
      _builder.clearContractStore()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.wasm.v1beta1.Genesis.Contract.copy(block: jmes.wasm.v1beta1.ContractKt.Dsl.() -> Unit): jmes.wasm.v1beta1.Genesis.Contract =
  jmes.wasm.v1beta1.ContractKt.Dsl._create(this.toBuilder()).apply { block() }._build()
