//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/wasm/v1beta1/genesis.proto

package jmes.wasm.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun genesisState(block: jmes.wasm.v1beta1.GenesisStateKt.Dsl.() -> Unit): jmes.wasm.v1beta1.Genesis.GenesisState =
  jmes.wasm.v1beta1.GenesisStateKt.Dsl._create(jmes.wasm.v1beta1.Genesis.GenesisState.newBuilder()).apply { block() }._build()
object GenesisStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.wasm.v1beta1.Genesis.GenesisState.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.wasm.v1beta1.Genesis.GenesisState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.wasm.v1beta1.Genesis.GenesisState = _builder.build()

    /**
     * <code>.jmes.wasm.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     */
    var params: jmes.wasm.v1beta1.Wasm.Params
      @JvmName("getParams")
      get() = _builder.getParams()
      @JvmName("setParams")
      set(value) {
        _builder.setParams(value)
      }
    /**
     * <code>.jmes.wasm.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     */
    fun clearParams() {
      _builder.clearParams()
    }
    /**
     * <code>.jmes.wasm.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the params field is set.
     */
    fun hasParams(): kotlin.Boolean {
      return _builder.hasParams()
    }

    /**
     * <code>uint64 last_code_id = 2 [(.gogoproto.customname) = "LastCodeID"];</code>
     */
    var lastCodeId: kotlin.Long
      @JvmName("getLastCodeId")
      get() = _builder.getLastCodeId()
      @JvmName("setLastCodeId")
      set(value) {
        _builder.setLastCodeId(value)
      }
    /**
     * <code>uint64 last_code_id = 2 [(.gogoproto.customname) = "LastCodeID"];</code>
     */
    fun clearLastCodeId() {
      _builder.clearLastCodeId()
    }

    /**
     * <code>uint64 last_instance_id = 3 [(.gogoproto.customname) = "LastInstanceID"];</code>
     */
    var lastInstanceId: kotlin.Long
      @JvmName("getLastInstanceId")
      get() = _builder.getLastInstanceId()
      @JvmName("setLastInstanceId")
      set(value) {
        _builder.setLastInstanceId(value)
      }
    /**
     * <code>uint64 last_instance_id = 3 [(.gogoproto.customname) = "LastInstanceID"];</code>
     */
    fun clearLastInstanceId() {
      _builder.clearLastInstanceId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class CodesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .jmes.wasm.v1beta1.Code codes = 4 [(.gogoproto.nullable) = false];</code>
     */
     val codes: com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Code, CodesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getCodesList()
      )
    /**
     * <code>repeated .jmes.wasm.v1beta1.Code codes = 4 [(.gogoproto.nullable) = false];</code>
     * @param value The codes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCodes")
    fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Code, CodesProxy>.add(value: jmes.wasm.v1beta1.Genesis.Code) {
      _builder.addCodes(value)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Code codes = 4 [(.gogoproto.nullable) = false];</code>
     * @param value The codes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCodes")
    inline operator fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Code, CodesProxy>.plusAssign(value: jmes.wasm.v1beta1.Genesis.Code) {
      add(value)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Code codes = 4 [(.gogoproto.nullable) = false];</code>
     * @param values The codes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCodes")
    fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Code, CodesProxy>.addAll(values: kotlin.collections.Iterable<jmes.wasm.v1beta1.Genesis.Code>) {
      _builder.addAllCodes(values)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Code codes = 4 [(.gogoproto.nullable) = false];</code>
     * @param values The codes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCodes")
    inline operator fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Code, CodesProxy>.plusAssign(values: kotlin.collections.Iterable<jmes.wasm.v1beta1.Genesis.Code>) {
      addAll(values)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Code codes = 4 [(.gogoproto.nullable) = false];</code>
     * @param index The index to set the value at.
     * @param value The codes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCodes")
    operator fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Code, CodesProxy>.set(index: kotlin.Int, value: jmes.wasm.v1beta1.Genesis.Code) {
      _builder.setCodes(index, value)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Code codes = 4 [(.gogoproto.nullable) = false];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCodes")
    fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Code, CodesProxy>.clear() {
      _builder.clearCodes()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class ContractsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .jmes.wasm.v1beta1.Contract contracts = 5 [(.gogoproto.nullable) = false];</code>
     */
     val contracts: com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Contract, ContractsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getContractsList()
      )
    /**
     * <code>repeated .jmes.wasm.v1beta1.Contract contracts = 5 [(.gogoproto.nullable) = false];</code>
     * @param value The contracts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addContracts")
    fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Contract, ContractsProxy>.add(value: jmes.wasm.v1beta1.Genesis.Contract) {
      _builder.addContracts(value)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Contract contracts = 5 [(.gogoproto.nullable) = false];</code>
     * @param value The contracts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignContracts")
    inline operator fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Contract, ContractsProxy>.plusAssign(value: jmes.wasm.v1beta1.Genesis.Contract) {
      add(value)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Contract contracts = 5 [(.gogoproto.nullable) = false];</code>
     * @param values The contracts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllContracts")
    fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Contract, ContractsProxy>.addAll(values: kotlin.collections.Iterable<jmes.wasm.v1beta1.Genesis.Contract>) {
      _builder.addAllContracts(values)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Contract contracts = 5 [(.gogoproto.nullable) = false];</code>
     * @param values The contracts to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllContracts")
    inline operator fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Contract, ContractsProxy>.plusAssign(values: kotlin.collections.Iterable<jmes.wasm.v1beta1.Genesis.Contract>) {
      addAll(values)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Contract contracts = 5 [(.gogoproto.nullable) = false];</code>
     * @param index The index to set the value at.
     * @param value The contracts to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setContracts")
    operator fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Contract, ContractsProxy>.set(index: kotlin.Int, value: jmes.wasm.v1beta1.Genesis.Contract) {
      _builder.setContracts(index, value)
    }/**
     * <code>repeated .jmes.wasm.v1beta1.Contract contracts = 5 [(.gogoproto.nullable) = false];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearContracts")
    fun com.google.protobuf.kotlin.DslList<jmes.wasm.v1beta1.Genesis.Contract, ContractsProxy>.clear() {
      _builder.clearContracts()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.wasm.v1beta1.Genesis.GenesisState.copy(block: jmes.wasm.v1beta1.GenesisStateKt.Dsl.() -> Unit): jmes.wasm.v1beta1.Genesis.GenesisState =
  jmes.wasm.v1beta1.GenesisStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()
