//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/wasm/v1beta1/tx.proto

package jmes.wasm.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun msgClearContractAdminResponse(block: jmes.wasm.v1beta1.MsgClearContractAdminResponseKt.Dsl.() -> Unit): jmes.wasm.v1beta1.Tx.MsgClearContractAdminResponse =
  jmes.wasm.v1beta1.MsgClearContractAdminResponseKt.Dsl._create(jmes.wasm.v1beta1.Tx.MsgClearContractAdminResponse.newBuilder()).apply { block() }._build()
object MsgClearContractAdminResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.wasm.v1beta1.Tx.MsgClearContractAdminResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.wasm.v1beta1.Tx.MsgClearContractAdminResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.wasm.v1beta1.Tx.MsgClearContractAdminResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.wasm.v1beta1.Tx.MsgClearContractAdminResponse.copy(block: jmes.wasm.v1beta1.MsgClearContractAdminResponseKt.Dsl.() -> Unit): jmes.wasm.v1beta1.Tx.MsgClearContractAdminResponse =
  jmes.wasm.v1beta1.MsgClearContractAdminResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
