//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/wasm/v1beta1/wasm.proto

package jmes.wasm.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun params(block: jmes.wasm.v1beta1.ParamsKt.Dsl.() -> Unit): jmes.wasm.v1beta1.Wasm.Params =
  jmes.wasm.v1beta1.ParamsKt.Dsl._create(jmes.wasm.v1beta1.Wasm.Params.newBuilder()).apply { block() }._build()
object ParamsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.wasm.v1beta1.Wasm.Params.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.wasm.v1beta1.Wasm.Params.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.wasm.v1beta1.Wasm.Params = _builder.build()

    /**
     * <code>uint64 max_contract_size = 1 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_size&#92;""];</code>
     */
    var maxContractSize: kotlin.Long
      @JvmName("getMaxContractSize")
      get() = _builder.getMaxContractSize()
      @JvmName("setMaxContractSize")
      set(value) {
        _builder.setMaxContractSize(value)
      }
    /**
     * <code>uint64 max_contract_size = 1 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_size&#92;""];</code>
     */
    fun clearMaxContractSize() {
      _builder.clearMaxContractSize()
    }

    /**
     * <code>uint64 max_contract_gas = 2 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_gas&#92;""];</code>
     */
    var maxContractGas: kotlin.Long
      @JvmName("getMaxContractGas")
      get() = _builder.getMaxContractGas()
      @JvmName("setMaxContractGas")
      set(value) {
        _builder.setMaxContractGas(value)
      }
    /**
     * <code>uint64 max_contract_gas = 2 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_gas&#92;""];</code>
     */
    fun clearMaxContractGas() {
      _builder.clearMaxContractGas()
    }

    /**
     * <code>uint64 max_contract_msg_size = 3 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_msg_size&#92;""];</code>
     */
    var maxContractMsgSize: kotlin.Long
      @JvmName("getMaxContractMsgSize")
      get() = _builder.getMaxContractMsgSize()
      @JvmName("setMaxContractMsgSize")
      set(value) {
        _builder.setMaxContractMsgSize(value)
      }
    /**
     * <code>uint64 max_contract_msg_size = 3 [(.gogoproto.moretags) = "yaml:&#92;"max_contract_msg_size&#92;""];</code>
     */
    fun clearMaxContractMsgSize() {
      _builder.clearMaxContractMsgSize()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.wasm.v1beta1.Wasm.Params.copy(block: jmes.wasm.v1beta1.ParamsKt.Dsl.() -> Unit): jmes.wasm.v1beta1.Wasm.Params =
  jmes.wasm.v1beta1.ParamsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
