//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/wasm/v1beta1/query.proto

package jmes.wasm.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryByteCodeResponse(block: jmes.wasm.v1beta1.QueryByteCodeResponseKt.Dsl.() -> Unit): jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeResponse =
  jmes.wasm.v1beta1.QueryByteCodeResponseKt.Dsl._create(jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeResponse.newBuilder()).apply { block() }._build()
object QueryByteCodeResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeResponse = _builder.build()

    /**
     * <code>bytes byte_code = 1;</code>
     */
    var byteCode: com.google.protobuf.ByteString
      @JvmName("getByteCode")
      get() = _builder.getByteCode()
      @JvmName("setByteCode")
      set(value) {
        _builder.setByteCode(value)
      }
    /**
     * <code>bytes byte_code = 1;</code>
     */
    fun clearByteCode() {
      _builder.clearByteCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeResponse.copy(block: jmes.wasm.v1beta1.QueryByteCodeResponseKt.Dsl.() -> Unit): jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeResponse =
  jmes.wasm.v1beta1.QueryByteCodeResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
