//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/wasm/v1beta1/query.proto

package jmes.wasm.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryContractInfoRequest(block: jmes.wasm.v1beta1.QueryContractInfoRequestKt.Dsl.() -> Unit): jmes.wasm.v1beta1.QueryOuterClass.QueryContractInfoRequest =
  jmes.wasm.v1beta1.QueryContractInfoRequestKt.Dsl._create(jmes.wasm.v1beta1.QueryOuterClass.QueryContractInfoRequest.newBuilder()).apply { block() }._build()
object QueryContractInfoRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.wasm.v1beta1.QueryOuterClass.QueryContractInfoRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.wasm.v1beta1.QueryOuterClass.QueryContractInfoRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.wasm.v1beta1.QueryOuterClass.QueryContractInfoRequest = _builder.build()

    /**
     * <code>string contract_address = 1;</code>
     */
    var contractAddress: kotlin.String
      @JvmName("getContractAddress")
      get() = _builder.getContractAddress()
      @JvmName("setContractAddress")
      set(value) {
        _builder.setContractAddress(value)
      }
    /**
     * <code>string contract_address = 1;</code>
     */
    fun clearContractAddress() {
      _builder.clearContractAddress()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.wasm.v1beta1.QueryOuterClass.QueryContractInfoRequest.copy(block: jmes.wasm.v1beta1.QueryContractInfoRequestKt.Dsl.() -> Unit): jmes.wasm.v1beta1.QueryOuterClass.QueryContractInfoRequest =
  jmes.wasm.v1beta1.QueryContractInfoRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
