//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/wasm/v1beta1/query.proto

package jmes.wasm.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryByteCodeRequest(block: jmes.wasm.v1beta1.QueryByteCodeRequestKt.Dsl.() -> Unit): jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeRequest =
  jmes.wasm.v1beta1.QueryByteCodeRequestKt.Dsl._create(jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeRequest.newBuilder()).apply { block() }._build()
object QueryByteCodeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeRequest = _builder.build()

    /**
     * <pre>
     * grpc-gateway_out does not support Go style CodID
     * </pre>
     *
     * <code>uint64 code_id = 1;</code>
     */
    var codeId: kotlin.Long
      @JvmName("getCodeId")
      get() = _builder.getCodeId()
      @JvmName("setCodeId")
      set(value) {
        _builder.setCodeId(value)
      }
    /**
     * <pre>
     * grpc-gateway_out does not support Go style CodID
     * </pre>
     *
     * <code>uint64 code_id = 1;</code>
     */
    fun clearCodeId() {
      _builder.clearCodeId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeRequest.copy(block: jmes.wasm.v1beta1.QueryByteCodeRequestKt.Dsl.() -> Unit): jmes.wasm.v1beta1.QueryOuterClass.QueryByteCodeRequest =
  jmes.wasm.v1beta1.QueryByteCodeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
