//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/wasm/v1beta1/query.proto

package jmes.wasm.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryContractStoreRequest(block: jmes.wasm.v1beta1.QueryContractStoreRequestKt.Dsl.() -> Unit): jmes.wasm.v1beta1.QueryOuterClass.QueryContractStoreRequest =
  jmes.wasm.v1beta1.QueryContractStoreRequestKt.Dsl._create(jmes.wasm.v1beta1.QueryOuterClass.QueryContractStoreRequest.newBuilder()).apply { block() }._build()
object QueryContractStoreRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.wasm.v1beta1.QueryOuterClass.QueryContractStoreRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.wasm.v1beta1.QueryOuterClass.QueryContractStoreRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.wasm.v1beta1.QueryOuterClass.QueryContractStoreRequest = _builder.build()

    /**
     * <code>string contract_address = 1;</code>
     */
    var contractAddress: kotlin.String
      @JvmName("getContractAddress")
      get() = _builder.getContractAddress()
      @JvmName("setContractAddress")
      set(value) {
        _builder.setContractAddress(value)
      }
    /**
     * <code>string contract_address = 1;</code>
     */
    fun clearContractAddress() {
      _builder.clearContractAddress()
    }

    /**
     * <code>bytes query_msg = 2 [(.gogoproto.casttype) = "encoding/json.RawMessage"];</code>
     */
    var queryMsg: com.google.protobuf.ByteString
      @JvmName("getQueryMsg")
      get() = _builder.getQueryMsg()
      @JvmName("setQueryMsg")
      set(value) {
        _builder.setQueryMsg(value)
      }
    /**
     * <code>bytes query_msg = 2 [(.gogoproto.casttype) = "encoding/json.RawMessage"];</code>
     */
    fun clearQueryMsg() {
      _builder.clearQueryMsg()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.wasm.v1beta1.QueryOuterClass.QueryContractStoreRequest.copy(block: jmes.wasm.v1beta1.QueryContractStoreRequestKt.Dsl.() -> Unit): jmes.wasm.v1beta1.QueryOuterClass.QueryContractStoreRequest =
  jmes.wasm.v1beta1.QueryContractStoreRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
