//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/market/v1beta1/genesis.proto

package jmes.market.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun genesisState(block: jmes.market.v1beta1.GenesisStateKt.Dsl.() -> Unit): jmes.market.v1beta1.Genesis.GenesisState =
  jmes.market.v1beta1.GenesisStateKt.Dsl._create(jmes.market.v1beta1.Genesis.GenesisState.newBuilder()).apply { block() }._build()
object GenesisStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.market.v1beta1.Genesis.GenesisState.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.market.v1beta1.Genesis.GenesisState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.market.v1beta1.Genesis.GenesisState = _builder.build()

    /**
     * <pre>
     * params defines all the paramaters of the module.
     * </pre>
     *
     * <code>.jmes.market.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     */
    var params: jmes.market.v1beta1.Market.Params
      @JvmName("getParams")
      get() = _builder.getParams()
      @JvmName("setParams")
      set(value) {
        _builder.setParams(value)
      }
    /**
     * <pre>
     * params defines all the paramaters of the module.
     * </pre>
     *
     * <code>.jmes.market.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     */
    fun clearParams() {
      _builder.clearParams()
    }
    /**
     * <pre>
     * params defines all the paramaters of the module.
     * </pre>
     *
     * <code>.jmes.market.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the params field is set.
     */
    fun hasParams(): kotlin.Boolean {
      return _builder.hasParams()
    }

    /**
     * <pre>
     * the gap between the JmesPool and the BasePool
     * </pre>
     *
     * <code>bytes jmes_pool_delta = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    var jmesPoolDelta: com.google.protobuf.ByteString
      @JvmName("getJmesPoolDelta")
      get() = _builder.getJmesPoolDelta()
      @JvmName("setJmesPoolDelta")
      set(value) {
        _builder.setJmesPoolDelta(value)
      }
    /**
     * <pre>
     * the gap between the JmesPool and the BasePool
     * </pre>
     *
     * <code>bytes jmes_pool_delta = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    fun clearJmesPoolDelta() {
      _builder.clearJmesPoolDelta()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.market.v1beta1.Genesis.GenesisState.copy(block: jmes.market.v1beta1.GenesisStateKt.Dsl.() -> Unit): jmes.market.v1beta1.Genesis.GenesisState =
  jmes.market.v1beta1.GenesisStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()
