//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/market/v1beta1/market.proto

package jmes.market.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun params(block: jmes.market.v1beta1.ParamsKt.Dsl.() -> Unit): jmes.market.v1beta1.Market.Params =
  jmes.market.v1beta1.ParamsKt.Dsl._create(jmes.market.v1beta1.Market.Params.newBuilder()).apply { block() }._build()
object ParamsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.market.v1beta1.Market.Params.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.market.v1beta1.Market.Params.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.market.v1beta1.Market.Params = _builder.build()

    /**
     * <code>bytes base_pool = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"base_pool&#92;""];</code>
     */
    var basePool: com.google.protobuf.ByteString
      @JvmName("getBasePool")
      get() = _builder.getBasePool()
      @JvmName("setBasePool")
      set(value) {
        _builder.setBasePool(value)
      }
    /**
     * <code>bytes base_pool = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"base_pool&#92;""];</code>
     */
    fun clearBasePool() {
      _builder.clearBasePool()
    }

    /**
     * <code>uint64 pool_recovery_period = 2 [(.gogoproto.moretags) = "yaml:&#92;"pool_recovery_period&#92;""];</code>
     */
    var poolRecoveryPeriod: kotlin.Long
      @JvmName("getPoolRecoveryPeriod")
      get() = _builder.getPoolRecoveryPeriod()
      @JvmName("setPoolRecoveryPeriod")
      set(value) {
        _builder.setPoolRecoveryPeriod(value)
      }
    /**
     * <code>uint64 pool_recovery_period = 2 [(.gogoproto.moretags) = "yaml:&#92;"pool_recovery_period&#92;""];</code>
     */
    fun clearPoolRecoveryPeriod() {
      _builder.clearPoolRecoveryPeriod()
    }

    /**
     * <code>bytes min_stability_spread = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"min_stability_spread&#92;""];</code>
     */
    var minStabilitySpread: com.google.protobuf.ByteString
      @JvmName("getMinStabilitySpread")
      get() = _builder.getMinStabilitySpread()
      @JvmName("setMinStabilitySpread")
      set(value) {
        _builder.setMinStabilitySpread(value)
      }
    /**
     * <code>bytes min_stability_spread = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"min_stability_spread&#92;""];</code>
     */
    fun clearMinStabilitySpread() {
      _builder.clearMinStabilitySpread()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.market.v1beta1.Market.Params.copy(block: jmes.market.v1beta1.ParamsKt.Dsl.() -> Unit): jmes.market.v1beta1.Market.Params =
  jmes.market.v1beta1.ParamsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
