//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/market/v1beta1/query.proto

package jmes.market.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryJmesPoolDeltaRequest(block: jmes.market.v1beta1.QueryJmesPoolDeltaRequestKt.Dsl.() -> Unit): jmes.market.v1beta1.QueryOuterClass.QueryJmesPoolDeltaRequest =
  jmes.market.v1beta1.QueryJmesPoolDeltaRequestKt.Dsl._create(jmes.market.v1beta1.QueryOuterClass.QueryJmesPoolDeltaRequest.newBuilder()).apply { block() }._build()
object QueryJmesPoolDeltaRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.market.v1beta1.QueryOuterClass.QueryJmesPoolDeltaRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.market.v1beta1.QueryOuterClass.QueryJmesPoolDeltaRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.market.v1beta1.QueryOuterClass.QueryJmesPoolDeltaRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.market.v1beta1.QueryOuterClass.QueryJmesPoolDeltaRequest.copy(block: jmes.market.v1beta1.QueryJmesPoolDeltaRequestKt.Dsl.() -> Unit): jmes.market.v1beta1.QueryOuterClass.QueryJmesPoolDeltaRequest =
  jmes.market.v1beta1.QueryJmesPoolDeltaRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
