//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/oracle/v1beta1/oracle.proto

package jmes.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun exchangeRateTuple(block: jmes.oracle.v1beta1.ExchangeRateTupleKt.Dsl.() -> Unit): jmes.oracle.v1beta1.Oracle.ExchangeRateTuple =
  jmes.oracle.v1beta1.ExchangeRateTupleKt.Dsl._create(jmes.oracle.v1beta1.Oracle.ExchangeRateTuple.newBuilder()).apply { block() }._build()
object ExchangeRateTupleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.oracle.v1beta1.Oracle.ExchangeRateTuple.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.oracle.v1beta1.Oracle.ExchangeRateTuple.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.oracle.v1beta1.Oracle.ExchangeRateTuple = _builder.build()

    /**
     * <code>string denom = 1 [(.gogoproto.moretags) = "yaml:&#92;"denom&#92;""];</code>
     */
    var denom: kotlin.String
      @JvmName("getDenom")
      get() = _builder.getDenom()
      @JvmName("setDenom")
      set(value) {
        _builder.setDenom(value)
      }
    /**
     * <code>string denom = 1 [(.gogoproto.moretags) = "yaml:&#92;"denom&#92;""];</code>
     */
    fun clearDenom() {
      _builder.clearDenom()
    }

    /**
     * <code>string exchange_rate = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"exchange_rate&#92;""];</code>
     */
    var exchangeRate: kotlin.String
      @JvmName("getExchangeRate")
      get() = _builder.getExchangeRate()
      @JvmName("setExchangeRate")
      set(value) {
        _builder.setExchangeRate(value)
      }
    /**
     * <code>string exchange_rate = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"exchange_rate&#92;""];</code>
     */
    fun clearExchangeRate() {
      _builder.clearExchangeRate()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.oracle.v1beta1.Oracle.ExchangeRateTuple.copy(block: jmes.oracle.v1beta1.ExchangeRateTupleKt.Dsl.() -> Unit): jmes.oracle.v1beta1.Oracle.ExchangeRateTuple =
  jmes.oracle.v1beta1.ExchangeRateTupleKt.Dsl._create(this.toBuilder()).apply { block() }._build()
