//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/oracle/v1beta1/genesis.proto

package jmes.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun feederDelegation(block: jmes.oracle.v1beta1.FeederDelegationKt.Dsl.() -> Unit): jmes.oracle.v1beta1.Genesis.FeederDelegation =
  jmes.oracle.v1beta1.FeederDelegationKt.Dsl._create(jmes.oracle.v1beta1.Genesis.FeederDelegation.newBuilder()).apply { block() }._build()
object FeederDelegationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.oracle.v1beta1.Genesis.FeederDelegation.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.oracle.v1beta1.Genesis.FeederDelegation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.oracle.v1beta1.Genesis.FeederDelegation = _builder.build()

    /**
     * <code>string feeder_address = 1;</code>
     */
    var feederAddress: kotlin.String
      @JvmName("getFeederAddress")
      get() = _builder.getFeederAddress()
      @JvmName("setFeederAddress")
      set(value) {
        _builder.setFeederAddress(value)
      }
    /**
     * <code>string feeder_address = 1;</code>
     */
    fun clearFeederAddress() {
      _builder.clearFeederAddress()
    }

    /**
     * <code>string validator_address = 2;</code>
     */
    var validatorAddress: kotlin.String
      @JvmName("getValidatorAddress")
      get() = _builder.getValidatorAddress()
      @JvmName("setValidatorAddress")
      set(value) {
        _builder.setValidatorAddress(value)
      }
    /**
     * <code>string validator_address = 2;</code>
     */
    fun clearValidatorAddress() {
      _builder.clearValidatorAddress()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.oracle.v1beta1.Genesis.FeederDelegation.copy(block: jmes.oracle.v1beta1.FeederDelegationKt.Dsl.() -> Unit): jmes.oracle.v1beta1.Genesis.FeederDelegation =
  jmes.oracle.v1beta1.FeederDelegationKt.Dsl._create(this.toBuilder()).apply { block() }._build()
