//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/oracle/v1beta1/oracle.proto

package jmes.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun params(block: jmes.oracle.v1beta1.ParamsKt.Dsl.() -> Unit): jmes.oracle.v1beta1.Oracle.Params =
  jmes.oracle.v1beta1.ParamsKt.Dsl._create(jmes.oracle.v1beta1.Oracle.Params.newBuilder()).apply { block() }._build()
object ParamsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.oracle.v1beta1.Oracle.Params.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.oracle.v1beta1.Oracle.Params.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.oracle.v1beta1.Oracle.Params = _builder.build()

    /**
     * <code>uint64 vote_period = 1 [(.gogoproto.moretags) = "yaml:&#92;"vote_period&#92;""];</code>
     */
    var votePeriod: kotlin.Long
      @JvmName("getVotePeriod")
      get() = _builder.getVotePeriod()
      @JvmName("setVotePeriod")
      set(value) {
        _builder.setVotePeriod(value)
      }
    /**
     * <code>uint64 vote_period = 1 [(.gogoproto.moretags) = "yaml:&#92;"vote_period&#92;""];</code>
     */
    fun clearVotePeriod() {
      _builder.clearVotePeriod()
    }

    /**
     * <code>string vote_threshold = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"vote_threshold&#92;""];</code>
     */
    var voteThreshold: kotlin.String
      @JvmName("getVoteThreshold")
      get() = _builder.getVoteThreshold()
      @JvmName("setVoteThreshold")
      set(value) {
        _builder.setVoteThreshold(value)
      }
    /**
     * <code>string vote_threshold = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"vote_threshold&#92;""];</code>
     */
    fun clearVoteThreshold() {
      _builder.clearVoteThreshold()
    }

    /**
     * <code>string reward_band = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"reward_band&#92;""];</code>
     */
    var rewardBand: kotlin.String
      @JvmName("getRewardBand")
      get() = _builder.getRewardBand()
      @JvmName("setRewardBand")
      set(value) {
        _builder.setRewardBand(value)
      }
    /**
     * <code>string reward_band = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"reward_band&#92;""];</code>
     */
    fun clearRewardBand() {
      _builder.clearRewardBand()
    }

    /**
     * <code>uint64 reward_distribution_window = 4 [(.gogoproto.moretags) = "yaml:&#92;"reward_distribution_window&#92;""];</code>
     */
    var rewardDistributionWindow: kotlin.Long
      @JvmName("getRewardDistributionWindow")
      get() = _builder.getRewardDistributionWindow()
      @JvmName("setRewardDistributionWindow")
      set(value) {
        _builder.setRewardDistributionWindow(value)
      }
    /**
     * <code>uint64 reward_distribution_window = 4 [(.gogoproto.moretags) = "yaml:&#92;"reward_distribution_window&#92;""];</code>
     */
    fun clearRewardDistributionWindow() {
      _builder.clearRewardDistributionWindow()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class WhitelistProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .jmes.oracle.v1beta1.Denom whitelist = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"whitelist&#92;"", (.gogoproto.castrepeated) = "DenomList"];</code>
     */
     val whitelist: com.google.protobuf.kotlin.DslList<jmes.oracle.v1beta1.Oracle.Denom, WhitelistProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getWhitelistList()
      )
    /**
     * <code>repeated .jmes.oracle.v1beta1.Denom whitelist = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"whitelist&#92;"", (.gogoproto.castrepeated) = "DenomList"];</code>
     * @param value The whitelist to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addWhitelist")
    fun com.google.protobuf.kotlin.DslList<jmes.oracle.v1beta1.Oracle.Denom, WhitelistProxy>.add(value: jmes.oracle.v1beta1.Oracle.Denom) {
      _builder.addWhitelist(value)
    }/**
     * <code>repeated .jmes.oracle.v1beta1.Denom whitelist = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"whitelist&#92;"", (.gogoproto.castrepeated) = "DenomList"];</code>
     * @param value The whitelist to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignWhitelist")
    inline operator fun com.google.protobuf.kotlin.DslList<jmes.oracle.v1beta1.Oracle.Denom, WhitelistProxy>.plusAssign(value: jmes.oracle.v1beta1.Oracle.Denom) {
      add(value)
    }/**
     * <code>repeated .jmes.oracle.v1beta1.Denom whitelist = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"whitelist&#92;"", (.gogoproto.castrepeated) = "DenomList"];</code>
     * @param values The whitelist to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllWhitelist")
    fun com.google.protobuf.kotlin.DslList<jmes.oracle.v1beta1.Oracle.Denom, WhitelistProxy>.addAll(values: kotlin.collections.Iterable<jmes.oracle.v1beta1.Oracle.Denom>) {
      _builder.addAllWhitelist(values)
    }/**
     * <code>repeated .jmes.oracle.v1beta1.Denom whitelist = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"whitelist&#92;"", (.gogoproto.castrepeated) = "DenomList"];</code>
     * @param values The whitelist to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllWhitelist")
    inline operator fun com.google.protobuf.kotlin.DslList<jmes.oracle.v1beta1.Oracle.Denom, WhitelistProxy>.plusAssign(values: kotlin.collections.Iterable<jmes.oracle.v1beta1.Oracle.Denom>) {
      addAll(values)
    }/**
     * <code>repeated .jmes.oracle.v1beta1.Denom whitelist = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"whitelist&#92;"", (.gogoproto.castrepeated) = "DenomList"];</code>
     * @param index The index to set the value at.
     * @param value The whitelist to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setWhitelist")
    operator fun com.google.protobuf.kotlin.DslList<jmes.oracle.v1beta1.Oracle.Denom, WhitelistProxy>.set(index: kotlin.Int, value: jmes.oracle.v1beta1.Oracle.Denom) {
      _builder.setWhitelist(index, value)
    }/**
     * <code>repeated .jmes.oracle.v1beta1.Denom whitelist = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"whitelist&#92;"", (.gogoproto.castrepeated) = "DenomList"];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearWhitelist")
    fun com.google.protobuf.kotlin.DslList<jmes.oracle.v1beta1.Oracle.Denom, WhitelistProxy>.clear() {
      _builder.clearWhitelist()
    }
    /**
     * <code>string slash_fraction = 6 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"slash_fraction&#92;""];</code>
     */
    var slashFraction: kotlin.String
      @JvmName("getSlashFraction")
      get() = _builder.getSlashFraction()
      @JvmName("setSlashFraction")
      set(value) {
        _builder.setSlashFraction(value)
      }
    /**
     * <code>string slash_fraction = 6 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"slash_fraction&#92;""];</code>
     */
    fun clearSlashFraction() {
      _builder.clearSlashFraction()
    }

    /**
     * <code>uint64 slash_window = 7 [(.gogoproto.moretags) = "yaml:&#92;"slash_window&#92;""];</code>
     */
    var slashWindow: kotlin.Long
      @JvmName("getSlashWindow")
      get() = _builder.getSlashWindow()
      @JvmName("setSlashWindow")
      set(value) {
        _builder.setSlashWindow(value)
      }
    /**
     * <code>uint64 slash_window = 7 [(.gogoproto.moretags) = "yaml:&#92;"slash_window&#92;""];</code>
     */
    fun clearSlashWindow() {
      _builder.clearSlashWindow()
    }

    /**
     * <code>string min_valid_per_window = 8 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"min_valid_per_window&#92;""];</code>
     */
    var minValidPerWindow: kotlin.String
      @JvmName("getMinValidPerWindow")
      get() = _builder.getMinValidPerWindow()
      @JvmName("setMinValidPerWindow")
      set(value) {
        _builder.setMinValidPerWindow(value)
      }
    /**
     * <code>string min_valid_per_window = 8 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"min_valid_per_window&#92;""];</code>
     */
    fun clearMinValidPerWindow() {
      _builder.clearMinValidPerWindow()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.oracle.v1beta1.Oracle.Params.copy(block: jmes.oracle.v1beta1.ParamsKt.Dsl.() -> Unit): jmes.oracle.v1beta1.Oracle.Params =
  jmes.oracle.v1beta1.ParamsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
