//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/oracle/v1beta1/query.proto

package jmes.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryMissCounterResponse(block: jmes.oracle.v1beta1.QueryMissCounterResponseKt.Dsl.() -> Unit): jmes.oracle.v1beta1.QueryOuterClass.QueryMissCounterResponse =
  jmes.oracle.v1beta1.QueryMissCounterResponseKt.Dsl._create(jmes.oracle.v1beta1.QueryOuterClass.QueryMissCounterResponse.newBuilder()).apply { block() }._build()
object QueryMissCounterResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.oracle.v1beta1.QueryOuterClass.QueryMissCounterResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.oracle.v1beta1.QueryOuterClass.QueryMissCounterResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.oracle.v1beta1.QueryOuterClass.QueryMissCounterResponse = _builder.build()

    /**
     * <pre>
     * miss_counter defines the oracle miss counter of a validator
     * </pre>
     *
     * <code>uint64 miss_counter = 1;</code>
     */
    var missCounter: kotlin.Long
      @JvmName("getMissCounter")
      get() = _builder.getMissCounter()
      @JvmName("setMissCounter")
      set(value) {
        _builder.setMissCounter(value)
      }
    /**
     * <pre>
     * miss_counter defines the oracle miss counter of a validator
     * </pre>
     *
     * <code>uint64 miss_counter = 1;</code>
     */
    fun clearMissCounter() {
      _builder.clearMissCounter()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.oracle.v1beta1.QueryOuterClass.QueryMissCounterResponse.copy(block: jmes.oracle.v1beta1.QueryMissCounterResponseKt.Dsl.() -> Unit): jmes.oracle.v1beta1.QueryOuterClass.QueryMissCounterResponse =
  jmes.oracle.v1beta1.QueryMissCounterResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
