//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/oracle/v1beta1/query.proto

package jmes.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryFeederDelegationResponse(block: jmes.oracle.v1beta1.QueryFeederDelegationResponseKt.Dsl.() -> Unit): jmes.oracle.v1beta1.QueryOuterClass.QueryFeederDelegationResponse =
  jmes.oracle.v1beta1.QueryFeederDelegationResponseKt.Dsl._create(jmes.oracle.v1beta1.QueryOuterClass.QueryFeederDelegationResponse.newBuilder()).apply { block() }._build()
object QueryFeederDelegationResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.oracle.v1beta1.QueryOuterClass.QueryFeederDelegationResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.oracle.v1beta1.QueryOuterClass.QueryFeederDelegationResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.oracle.v1beta1.QueryOuterClass.QueryFeederDelegationResponse = _builder.build()

    /**
     * <pre>
     * feeder_addr defines the feeder delegation of a validator
     * </pre>
     *
     * <code>string feeder_addr = 1;</code>
     */
    var feederAddr: kotlin.String
      @JvmName("getFeederAddr")
      get() = _builder.getFeederAddr()
      @JvmName("setFeederAddr")
      set(value) {
        _builder.setFeederAddr(value)
      }
    /**
     * <pre>
     * feeder_addr defines the feeder delegation of a validator
     * </pre>
     *
     * <code>string feeder_addr = 1;</code>
     */
    fun clearFeederAddr() {
      _builder.clearFeederAddr()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.oracle.v1beta1.QueryOuterClass.QueryFeederDelegationResponse.copy(block: jmes.oracle.v1beta1.QueryFeederDelegationResponseKt.Dsl.() -> Unit): jmes.oracle.v1beta1.QueryOuterClass.QueryFeederDelegationResponse =
  jmes.oracle.v1beta1.QueryFeederDelegationResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
