//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/oracle/v1beta1/query.proto

package jmes.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryTobinTaxResponse(block: jmes.oracle.v1beta1.QueryTobinTaxResponseKt.Dsl.() -> Unit): jmes.oracle.v1beta1.QueryOuterClass.QueryTobinTaxResponse =
  jmes.oracle.v1beta1.QueryTobinTaxResponseKt.Dsl._create(jmes.oracle.v1beta1.QueryOuterClass.QueryTobinTaxResponse.newBuilder()).apply { block() }._build()
object QueryTobinTaxResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.oracle.v1beta1.QueryOuterClass.QueryTobinTaxResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.oracle.v1beta1.QueryOuterClass.QueryTobinTaxResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.oracle.v1beta1.QueryOuterClass.QueryTobinTaxResponse = _builder.build()

    /**
     * <pre>
     * tobin_taxe defines the tobin tax of a denom
     * </pre>
     *
     * <code>string tobin_tax = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    var tobinTax: kotlin.String
      @JvmName("getTobinTax")
      get() = _builder.getTobinTax()
      @JvmName("setTobinTax")
      set(value) {
        _builder.setTobinTax(value)
      }
    /**
     * <pre>
     * tobin_taxe defines the tobin tax of a denom
     * </pre>
     *
     * <code>string tobin_tax = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    fun clearTobinTax() {
      _builder.clearTobinTax()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.oracle.v1beta1.QueryOuterClass.QueryTobinTaxResponse.copy(block: jmes.oracle.v1beta1.QueryTobinTaxResponseKt.Dsl.() -> Unit): jmes.oracle.v1beta1.QueryOuterClass.QueryTobinTaxResponse =
  jmes.oracle.v1beta1.QueryTobinTaxResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
