//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/oracle/v1beta1/query.proto

package jmes.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryExchangeRateRequest(block: jmes.oracle.v1beta1.QueryExchangeRateRequestKt.Dsl.() -> Unit): jmes.oracle.v1beta1.QueryOuterClass.QueryExchangeRateRequest =
  jmes.oracle.v1beta1.QueryExchangeRateRequestKt.Dsl._create(jmes.oracle.v1beta1.QueryOuterClass.QueryExchangeRateRequest.newBuilder()).apply { block() }._build()
object QueryExchangeRateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.oracle.v1beta1.QueryOuterClass.QueryExchangeRateRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.oracle.v1beta1.QueryOuterClass.QueryExchangeRateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.oracle.v1beta1.QueryOuterClass.QueryExchangeRateRequest = _builder.build()

    /**
     * <pre>
     * denom defines the denomination to query for.
     * </pre>
     *
     * <code>string denom = 1;</code>
     */
    var denom: kotlin.String
      @JvmName("getDenom")
      get() = _builder.getDenom()
      @JvmName("setDenom")
      set(value) {
        _builder.setDenom(value)
      }
    /**
     * <pre>
     * denom defines the denomination to query for.
     * </pre>
     *
     * <code>string denom = 1;</code>
     */
    fun clearDenom() {
      _builder.clearDenom()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.oracle.v1beta1.QueryOuterClass.QueryExchangeRateRequest.copy(block: jmes.oracle.v1beta1.QueryExchangeRateRequestKt.Dsl.() -> Unit): jmes.oracle.v1beta1.QueryOuterClass.QueryExchangeRateRequest =
  jmes.oracle.v1beta1.QueryExchangeRateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
