//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/oracle/v1beta1/genesis.proto

package jmes.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun tobinTax(block: jmes.oracle.v1beta1.TobinTaxKt.Dsl.() -> Unit): jmes.oracle.v1beta1.Genesis.TobinTax =
  jmes.oracle.v1beta1.TobinTaxKt.Dsl._create(jmes.oracle.v1beta1.Genesis.TobinTax.newBuilder()).apply { block() }._build()
object TobinTaxKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.oracle.v1beta1.Genesis.TobinTax.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.oracle.v1beta1.Genesis.TobinTax.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.oracle.v1beta1.Genesis.TobinTax = _builder.build()

    /**
     * <code>string denom = 1;</code>
     */
    var denom: kotlin.String
      @JvmName("getDenom")
      get() = _builder.getDenom()
      @JvmName("setDenom")
      set(value) {
        _builder.setDenom(value)
      }
    /**
     * <code>string denom = 1;</code>
     */
    fun clearDenom() {
      _builder.clearDenom()
    }

    /**
     * <code>string tobin_tax = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    var tobinTax: kotlin.String
      @JvmName("getTobinTax")
      get() = _builder.getTobinTax()
      @JvmName("setTobinTax")
      set(value) {
        _builder.setTobinTax(value)
      }
    /**
     * <code>string tobin_tax = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    fun clearTobinTax() {
      _builder.clearTobinTax()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.oracle.v1beta1.Genesis.TobinTax.copy(block: jmes.oracle.v1beta1.TobinTaxKt.Dsl.() -> Unit): jmes.oracle.v1beta1.Genesis.TobinTax =
  jmes.oracle.v1beta1.TobinTaxKt.Dsl._create(this.toBuilder()).apply { block() }._build()
