//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/treasury/v1beta1/query.proto

package jmes.treasury.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryTaxProceedsRequest(block: jmes.treasury.v1beta1.QueryTaxProceedsRequestKt.Dsl.() -> Unit): jmes.treasury.v1beta1.QueryOuterClass.QueryTaxProceedsRequest =
  jmes.treasury.v1beta1.QueryTaxProceedsRequestKt.Dsl._create(jmes.treasury.v1beta1.QueryOuterClass.QueryTaxProceedsRequest.newBuilder()).apply { block() }._build()
object QueryTaxProceedsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.treasury.v1beta1.QueryOuterClass.QueryTaxProceedsRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.treasury.v1beta1.QueryOuterClass.QueryTaxProceedsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.treasury.v1beta1.QueryOuterClass.QueryTaxProceedsRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.treasury.v1beta1.QueryOuterClass.QueryTaxProceedsRequest.copy(block: jmes.treasury.v1beta1.QueryTaxProceedsRequestKt.Dsl.() -> Unit): jmes.treasury.v1beta1.QueryOuterClass.QueryTaxProceedsRequest =
  jmes.treasury.v1beta1.QueryTaxProceedsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
