//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: jmes/treasury/v1beta1/query.proto

package jmes.treasury.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryRewardWeightResponse(block: jmes.treasury.v1beta1.QueryRewardWeightResponseKt.Dsl.() -> Unit): jmes.treasury.v1beta1.QueryOuterClass.QueryRewardWeightResponse =
  jmes.treasury.v1beta1.QueryRewardWeightResponseKt.Dsl._create(jmes.treasury.v1beta1.QueryOuterClass.QueryRewardWeightResponse.newBuilder()).apply { block() }._build()
object QueryRewardWeightResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: jmes.treasury.v1beta1.QueryOuterClass.QueryRewardWeightResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jmes.treasury.v1beta1.QueryOuterClass.QueryRewardWeightResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jmes.treasury.v1beta1.QueryOuterClass.QueryRewardWeightResponse = _builder.build()

    /**
     * <code>string reward_weight = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    var rewardWeight: kotlin.String
      @JvmName("getRewardWeight")
      get() = _builder.getRewardWeight()
      @JvmName("setRewardWeight")
      set(value) {
        _builder.setRewardWeight(value)
      }
    /**
     * <code>string reward_weight = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     */
    fun clearRewardWeight() {
      _builder.clearRewardWeight()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun jmes.treasury.v1beta1.QueryOuterClass.QueryRewardWeightResponse.copy(block: jmes.treasury.v1beta1.QueryRewardWeightResponseKt.Dsl.() -> Unit): jmes.treasury.v1beta1.QueryOuterClass.QueryRewardWeightResponse =
  jmes.treasury.v1beta1.QueryRewardWeightResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
